FROM ubuntu:18.04
MAINTAINER zxc25077667@gmail.com
LABEL description="terminal game web server" version="0.0" owner="scc"

#install packages
#installing ssh
RUN echo "start install the env."
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:root' | chpasswd
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

#install game handler
RUN apt-get install git -y
RUN git clone https://github.com/25077667/terminal-game.git ~/.
RUN ~/terminal-game/init.sh

#set game handle server
EXPOSE 3000

#set normal html at 80 port
EXPOSE 80

#set ssh
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
ENTRYPOINT service ssh restart && bash

VOLUME ~/log
VOLUME ~/db/